# This is your main playbook you will run with:
# ansible-playbook site.yml
# You can kick off everything from this playbook.
# Or, you can create separate playbooks in this directory for specific orchestration events.

---
- name: Configure system-level entities
  hosts: rpi
  become: yes
  become_method: sudo

  roles:
  - common

- name: Install and configure Opencanary app
  hosts: rpi
  become: yes
  become_method: sudo
  become_user: opencanary

  tasks:
  - import_role:
      name: opencanary

# vi: ts=2 sts=2 sw=2 expandtab:
