---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
- name: debian_9_stretch
  image: debian:stretch
- name: debian_8_jessie
  image: debian:jessie

# Envs expected to fail:
- name: debian_10_testing
  image: debian:testing
- name: debian_11_unstable
  image: debian:unstable
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
