---  # vim:se ft=ansible:
- name: Set up pre-requisites
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python
  roles:
  - role: common

- name: Converge
  hosts: all
  roles:
  - role: opencanary
