---
- name: Install Opencanary under the user-specific virtualenv
  pip:
    name:
    - patron-it-opencanary[remote-logging]{{ opencanary_version | default('') }}
    state: >-
      {{ opencanary_version | default('') | ternary('present', 'latest') }}
    virtualenv: >-
      {{ opencanary_virtualenv }}
    virtualenv_python: python3
# vi: ts=2 sts=2 sw=2 expandtab:
