---
- name: Copy venv constraints for OpenCanary
  copy:
    src: opencanary-venv-constraints.txt
    dest: ~/
- name: Install Opencanary under the user-specific virtualenv
  pip:
    name:
    - >-
      {{ opencanary_dist }}[remote_logging]{{ opencanary_version | default('') }}
    extra_args: -c ~/opencanary-venv-constraints.txt
    state: >-
      {{ opencanary_version | default('') | ternary('present', 'latest') }}
    virtualenv: >-
      ~/{{ opencanary_virtualenv }}
    virtualenv_python: python3
- name: Set up a config file for opencanary
  template:
    src: opencanary.conf.j2
    dest: ~/opencanary.conf
  notify: restart opencanary
- name: Ensure that linger is enabled for opencanary
  block:
  - name: Check whether linger is enabled
    stat:
      path: /var/lib/systemd/linger/{{ ansible_user_id }}
    register: linger_file
  - name: Enable linger if needed
    command: loginctl enable-linger {{ ansible_user_id }}
    become: true
    become_user: root
    when: not linger_file.stat.exists
- name: Set up a systemd unit file for opencanary
  template:
    src: opencanary.service.j2
    dest: /etc/systemd/user/opencanary.service
  become: true
  become_user: root
  notify: restart opencanary
- name: Ensure that opencanary service is started
  systemd:
    name: opencanary
    enabled: true
    daemon_reload: true
    state: started
    scope: user
# vi: ts=2 sts=2 sw=2 expandtab:
