---
- name: >
    Install ACL to enable Ansible use tmp dir when becoming an unprivileged user
  apt:
    name:
    - acl
    state: latest
- name: Enable automatic reboots after unattended upgrades
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: >-
      Unattended-Upgrade::Automatic-Reboot "true";
    line: >-
      Unattended-Upgrade::Automatic-Reboot "true";
    state: present
- name: Install system software prerequisites
  apt:
    name:
    - git
    - jq
    - mc
    - openvpn
    - samba
    - unattended-upgrades
    state: latest
- name: Install pythonic prerequisites
  apt:
    name:
    - python3-setuptools
    - python3-venv
    - python3-virtualenv
    - virtualenv
    state: latest
- name: Create a user for opencanary app
  user:
    create_home: true
    name: opencanary
    state: present
    uid: 2001  # to be consistent across updates, changes, reinstalls
# vi: ts=2 sts=2 sw=2 expandtab:
